version: '3.9'

volumes:
  ratesdb-data:

services:
  api:
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    image: ${RATES_IMAGE_REPOSITORY:-gledi/rates}:${RATES_IMAGE_TAG:-develop}
    container_name: rates-api
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    volumes:
      - ./rates/:/app/rates/
      - ./containers/scripts/:/app/scripts/
    depends_on:
      - db
    command: ["/bin/bash", "/app/scripts/start-app-dev.sh"]

  db:
    image: postgres:14-alpine
    container_name: rates-db
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - ratesdb-data:/var/lib/postgresql/data
      - ./containers/initdb.d:/docker-entrypoint-initdb.d
