version: '3.9'

volumes:
  ratesdb-testing-data:

services:
  testapi:
    build:
      context: .
      dockerfile: ./containers/Dockerfile
      args:
        - ENVIRONMENT=test
    image: ${REPOSITORY:-gledi/rates}:${TEST_TAG:-testing}
    container_name: rates-api-testing
    env_file:
      - .env.testing
    volumes:
      - ./rates/:/app/rates/
      - ./tests/:/app/tests/
      - ./containers/scripts/:/app/scripts/
      - ./pyproject.toml:/app/pyproject.toml
    depends_on:
      - db
    command: ["/bin/bash", "/app/scripts/start-app-test.sh"]

  db:
    image: postgres:14-alpine
    container_name: rates-db-testing
    restart: unless-stopped
    env_file:
      - .env.testing
    volumes:
      - ratesdb-testing-data:/var/lib/postgresql/data
      - ./containers/initdb_testing.d:/docker-entrypoint-initdb.d
